### ISSUE TITLE
API admin breaks when trying to post multiple, successive updates

### ISSUE THREAD

**Issue by toconnell** [theLaborInVain/kdm-manager-api#1]
> User OID: 565f3d67421aa95c4af1e230
> Method: POST
> URL: http://api.kdm-manager.com/admin/notifications/new
> JSON: {'expiration': 'manual', 'type': 'webapp_alert', 'title': 'Welcome to the other side!', 'body': 'https://kdm-manager.com has been redeployed and is now using version 1.0.000 of the KDM API in production! If you encounter any issues, please use GitHub to report them: https://github.com/toconnell/kdm-manager/issues. Thanks for using the Manager!', 'created_by': 'toconnell@tyrannybelle.com', 'sub_type': 'kpi', 'created_on': datetime.datetime(2019, 7, 19, 14, 1, 19, 636193)}
> 
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
 rv = self.dispatch_request()
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask_httpauth.py", line 104, in decorated
 return f(*args, **kwargs)
File "/home/toconnell/kdm-manager-api/app/routes.py", line 433, in admin_notifications
 return admin.get_notifications(method)
File "/home/toconnell/kdm-manager-api/app/admin/__init__.py", line 35, in get_notifications
 A = notifications.Alert()
File "/home/toconnell/kdm-manager-api/app/admin/notifications.py", line 53, in __init__
 self.new()
File "/home/toconnell/kdm-manager-api/app/admin/notifications.py", line 73, in new
 self.alert['created_by'] = ObjectId(self.alert['created_by'])
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/bson/objectid.py", line 125, in __init__
 self.__validate(oid)
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/bson/objectid.py", line 221, in __validate
 _raise_invalid_id(oid)
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/bson/objectid.py", line 67, in _raise_invalid_id
 " or a 24-character hex string" % oid)
bson.errors.InvalidId: 'toconnell@tyrannybelle.com' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```

**Comment by toconnell** [comment]
This was previously only refreshing after an update. Now it's refreshing every 120 seconds, just like the other stuff in the admin panel.

**Comment by toconnell** [comment]
Evidently this broke when we started putting user data in scope on the admin panel. Previously, you could pick a user from a drop-down, but that went away when we started using the user info from the environment/Flask.

**Comment by toconnell** [comment]
This is fixed. I also tuned up the method in _routes.py_ that dumps the user document so that all the non-string data gets serialized.
