### ISSUE TITLE
/game_asset w/ no POST params fails

### ISSUE THREAD

**Issue by toconnell** [theLaborInVain/kdm-manager-api#14]
> User OID: 666
> Method: GET
> URL: http://api.kdm-manager.com/game_asset
> JSON: None
>
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
 rv = self.dispatch_request()
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager-api/app/utils/crossdomain.py", line 56, in wrapped_function
 resp = flask.make_response(func(*args, **kwargs))
File "/home/toconnell/kdm-manager-api/app/routes.py", line 245, in list_game_assets
 assets.list(game_assets=True),
File "/home/toconnell/kdm-manager-api/app/assets/__init__.py", line 134, in list
 collectionObject = dump_asset(collection_name, return_type=object)
NameError: name 'dump_asset' is not defined
```

**Comment by toconnell** [comment]
This is a dupe of https://github.com/theLaborInVain/kdm-manager-api/issues/19
