### ISSUE TITLE
Handle 'Method Not Allowed' failures without sending an alert email

### ISSUE THREAD

**Issue by toconnell** [theLaborInVain/kdm-manager-api#23]
> User OID: 666
> Method: GET
> URL: http://api.kdm-manager.com/login
> JSON: None
>
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
 rv = self.dispatch_request()
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
 self.raise_routing_exception(req)
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
 raise request.routing_exception
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
 self.url_adapter.match(return_rule=True)
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1783, in match
 raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
```

**Comment by toconnell** [comment]
This is handled in the next release of the API.
