### ISSUE TITLE
Users: str type subscriber data causes settlements to fail to load

### ISSUE THREAD

**Issue by toconnell** [theLaborInVain/kdm-manager-api#25]
> User OID: 5a25b9048740d906eb6d25f9
> Method: GET
> URL: http://api.kdm-manager.com/user/dashboard/5a25b9048740d906eb6d25f9
> JSON: None
>
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
 rv = self.dispatch_request()
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager-api/app/utils/crossdomain.py", line 56, in wrapped_function
 resp = flask.make_response(func(*args, **kwargs))
File "/home/toconnell/kdm-manager-api/app/routes.py", line 497, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager-api/app/models/users.py", line 1181, in request_response
 return Response(response=self.serialize('dashboard'), status=200, mimetype="application/json")
File "/home/toconnell/kdm-manager-api/app/models/users.py", line 486, in serialize
 output["dashboard"]["friends"] = self.get_friends(return_type=list)
File "/home/toconnell/kdm-manager-api/app/models/users.py", line 876, in get_friends
 campaigns = self.get_settlements(qualifier="player")
File "/home/toconnell/kdm-manager-api/app/models/users.py", line 953, in get_settlements
 settlements_owned = self.get_settlements()
File "/home/toconnell/kdm-manager-api/app/models/users.py", line 975, in get_settlements
 if sub_level >= 1:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

**Comment by toconnell** [comment]
This is actually kind of amazing, given how much effort went into patching this for 1.0.0.

After five years of doing this, you'd think I would be better at this (but you would be wrong).

**Comment by toconnell** [comment]
Alright, so it looks like the fuck-up here is that the code under _normalize()_ that switched 'patron' to 'subscriber' in the 1.0.0 release just picks up the old dict and sets it down without duck-typing the string to an int.

![image](https://user-images.githubusercontent.com/48043/99459808-4fbf4b00-28f4-11eb-8544-8dceac794131.png)

**Comment by toconnell** [comment]
Fixed in the next release:

```
@@ -1157,6 +1160,14 @@ class User(models.UserAsset):
             self.logger.warn("%s Added 'subscriber' dict to user!" % self)
             self.perform_save = True

+        if isinstance(self.user['subscriber']['level'], str):
+            warn = "%s Subscriber 'level' is str type! Normalizing to int..."
+            self.logger.warn(warn % self)
+            self.user['subscriber']['level'] = int(
+                self.user['subscriber']['level']
+            )
+            self.perform_save = True
+
         if self.perform_save:
             self.save()
```
