### ISSUE TITLE
World: 'total_subscribers' query is returning only recent users. 

### ISSUE THREAD

**Issue by toconnell** [theLaborInVain/kdm-manager-api#4]
Here's test and prod side by side:

![issue_4_dev](https://user-images.githubusercontent.com/48043/61739028-3a163180-ad51-11e9-9643-151b5c9f7a60.PNG)
![issue_4_prod](https://user-images.githubusercontent.com/48043/61739029-3a163180-ad51-11e9-9098-3aa674f4be81.PNG)

**Comment by toconnell** [comment]
Now that the query debugger is fixed, we can troubleshoot this guy in production after the next release goes out.

**Comment by toconnell** [comment]
This is because the query is looking for users with the 'subscriber' key (rather than the deprecated 'patron' key). Looks like we're gonna need a mass-normalize to fix this one...

**Comment by toconnell** [comment]
Running the patch in production actually causes a problem because it initializes the users with the broken attributes first:
```

toconnell@advanced-kdm-manager:~/kdm-manager-api$ ./admin.sh --patch normalize_subscriber_level
 * interpreter: /home/toconnell/kdm-manager-api/venv/bin/python (Python 3.6.8)
 *  PYTHONPATH: /home/toconnell/kdm-manager-api
 *         API: version: 1.2.7, mdb: kdm-manager
 Found 397 users with the 'patron' attribute!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "app/admin/__main__.py", line 682, in <module>
    ADMIN_OBJECT.process_args()
  File "app/admin/__main__.py", line 355, in process_args
    patch_method()
  File "/home/toconnell/kdm-manager-api/app/admin/patch.py", line 34, in normalize_subscriber_level
    user_object = users.User(_id=patron['_id'])
  File "/home/toconnell/kdm-manager-api/app/models/users.py", line 377, in __init__
    if self.user['subscriber']['level'] >= 3:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

**Comment by toconnell** [comment]
Monkey patched the int/str problem and ran the patch successfully:

```
toconnell@advanced-kdm-manager:~/kdm-manager-api$ ./admin.sh --patch normalize_subscriber_level
 * interpreter: /home/toconnell/kdm-manager-api/venv/bin/python (Python 3.6.8)
 *  PYTHONPATH: /home/toconnell/kdm-manager-api
 *         API: version: 1.2.7, mdb: kdm-manager

 Found 391 users with the 'patron' attribute!
 Initialized 0 user objects successfully!
 World query 'subscribers_by_level' now looks like:

comment:             A dictionary that includes subscriber counts by subscriber level.
created_on:          2019-07-25 08:49:49.786942
handle:              subscribers_by_level
max_age:             900
name:                Subscribers by Level
value:               [{'level': 1, 'count': 37}, {'level': 2, 'count': 340}]
value_type:          list

 Patch applied successfully!
```

**Comment by toconnell** [comment]
...and we're back:
```
toconnell@advanced-kdm-manager:~/kdm-manager-api$ ./world.sh --debug total_subscribers
comment:             The total number of users who subscribe to the application (at any level).
created_on:          2019-07-25 08:50:51.808126
handle:              total_subscribers
max_age:             900
name:                Total Subscribers
value:               377
value_type:          int
```
