### ISSUE TITLE
World: killboard error while incrementing keys

### ISSUE THREAD

**Issue by toconnell** [theLaborInVain/kdm-manager-api#5]
From the production world logs:
```
[2019-07-23 16:39:21] ERROR:    exception caught while refreshing 'killboard' asset!
[2019-07-23 16:39:21] ERROR:    'butcher'
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager-api/app/world/__init__.py", line 165, in refresh_asset
    self.update_asset_dict(asset_dict)
  File "/home/toconnell/kdm-manager-api/app/world/__init__.py", line 219, in update_asset_dict
    fresh_results = update_method()
  File "/home/toconnell/kdm-manager-api/app/world/__init__.py", line 921, in killboard
    killboard[d["type"]][d["handle"]]["count"] += 1
KeyError: 'butcher'
```

**Comment by toconnell** [comment]
From test:
```
toconnell@mona:~/kdm-manager-api$ ./world.sh --debug killboard
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "app/world/__main__.py", line 75, in <module>
    results = WORLD.debug_query(options.debug_query)
  File "/home/toconnell/kdm-manager-api/app/world/__init__.py", line 395, in debug_query
    results = self.update_asset_dict(asset_dict)
  File "/home/toconnell/kdm-manager-api/app/world/__init__.py", line 266, in update_asset_dict
    fresh_results = update_method()
  File "/home/toconnell/kdm-manager-api/app/world/__init__.py", line 967, in killboard
    killboard[d["type"]][d["handle"]]["count"] += 1
KeyError: 'white_lion'
```

Looks like we might just have a good, old fashioned "Python3 does basic shit without any kind of backwards compatibility" issue...

**Comment by toconnell** [comment]
The fix for this was to bite the bullet early and implement the _KillboardObject_, which normalizes killboard entries with invalid types to have their correct type (according to _models.assets.monsters.py_). 

At any rate, this will be fixed in the next release.
